clear
mw0 = uifigure('Name', 'mw0');
mw0.Position = [30 60 450 650];
g1 = uigridlayout(mw0, [3 2]);
g1.RowHeight = {'fit', 'fit', '1X'};
g1.ColumnWidth = {'fit', '1x'};
imageLabel = uiimage(g1);
imageLabel.Layout.Row = 1;
imageLabel.Layout.Column = [1 2];
imageLabel.ImageSource = fullfile('cat.jpg');
mw1 = uiaxes(g1);
mw1.Layout.Row = 2;
mw1.Layout.Column = [1 2];
[x, y, z] = peaks;
f1 = surfl(mw1, x, y, z); 
axis(mw1, [-3 3 -3 3 -8 8])
colormap(mw1, [0.5 0.5 0.5])
cdata = mw1.Colormap;
initcdata = cdata;
scroll1 = uicontrol('parent', mw0, ...
                    'style', 'slider', ...
                    'min', 0, ...
                    'max', 1, ...
                    'value', cdata(1), ...
                    'position', [20 150 400 20], ...
                    'callback', ['srl1k=get(scroll1, ''value'');, ', ...
                                 'cdata(1)=srl1k;, ', ...
                                 'set(mw1, ''colormap'', cdata);']);
scroll2 = uicontrol('parent', mw0, ...
                    'style', 'slider', ...
                    'min', 0, ...
                    'max', 1, ...
                    'value', cdata(2), ...
                    'position', [20 100 400 20], ...
                    'callback', ['srl2k=get(scroll2, ''value'');,', ...
                                 'cdata(2)=srl2k;,', ...
                                 'set(mw1, ''colormap'', cdata); ']);
scroll3 = uicontrol('parent', mw0, ...
                    'style', 'slider', ...
                    'min', 0, ...
                    'max', 1, ...
                    'value', cdata(3), ...
                    'position', [20 50 400 20], ...
                    'callback', ['srl3k=get(scroll3, ''value'');, ', ...
                                 'cdata(3)=srl3k;, ', ...
                                 'set(mw1, ''colormap'', cdata);']);
Labell = uicontrol('parent', mw0, ...
                   'style', 'text', ...
                   'string', '更改紅色成份', ...
                   'position', [20 170 400 20]);
Label2 = uicontrol('parent', mw0, ...
                   'style', 'text', ...
                   'string', '更改綠色成份', ...
                   'position', [20 120 400 20]);

Label3 = uicontrol('parent', mw0, ...
                   'style', 'text', ...
                   'string', '更改藍色成份', ...
                   'position', [20 70 400 20]);
Label4 = uicontrol('parent', mw0, ...
                   'style', 'text', ...
                   'string', '更改peaks函數顏色成份', ...
                   'position', [10 450 150 20]);
Button1 = uicontrol('parent', mw0, ...
                    'style', 'pushbutton', ...
                    'string', 'Reset', ...
                    'position', [120 5 60 40], ...
                    'callback', ['set(scroll1, ''value'', initcdata(1));, ', ...
                                 'set(scroll2, ''value'', initcdata(2));, ', ...
                                 'set(scroll3, ''value'', initcdata(3));, ', ...
                                 'set(mw1, ''colormap'', initcdata);']);
Button2 = uicontrol('parent', mw0, ...
                    'style', 'pushbutton', ...
                    'string', 'Close', ...
                    'position', [300 5 60 40], ...
                    'callback', 'close');